dependencies = [ ]
license = "MIT"
spec = "https://rawgit.com/caridy/intl-plural-rules-spec/master/index.html"
repo = "https://github.com/formatjs/formatjs/blob/master/packages/intl-pluralrules/polyfill.js"
docs = "https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/PluralRules"
notes = [
  "Locales must be specified separately by prefixing the locale name with `Intl.PluralRules~locale`, eg `Intl.PluralRules~locale.en-GB`."
]

[browsers]
android = "<63"
ie = "<18"
ie_mob = "*"
firefox = "<58"
opera = "<50"
chrome = "<63"
safari = "*"
ios_saf = "*"
firefox_mob = "<58"
samsung_mob = "*"

[build]
minify = false

[install]
module = "@formatjs/intl-pluralrules"
paths = [ "dist/polyfill.js" ]
postinstall = "update.task.js"

