language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    - secure: YOIP+tZnq594Uz+TVKGeyt6OAraQYLGZO6K97Esi6R5gDL2nyIEG++6E8bXSL6+JQ9dpMvDjNoYj09J+TlJrb2vt441FAGcFOStTfjIue1BwfP7pVHEKKRcuxmNizFy8sqV+O1/MwB3uOkmBx4L9dOml9+H11yTN/TO2DFfKS3w=
    - secure: GtX1bvvXYammVxJwBTj5l1aFiyUTW6pH5UBaJldDztlasq9Un4GCK/aLGzgaSeQ00mvc3MCQJTEH2y6vl0KEIYAsRnXCylITuoFKuYNNccpNYdr+E/XJPhbgVtlUel/STP8MgO+PV6iqwQvoL/B8835hIx9sUL82qrbopWHMZOQ=
notifications:
  email: false
before_script: npm install -g karma-cli
