version: 2
jobs:
  lint_js:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        command: npm run lint
  unit_tests:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        command: npm run test-library
  publish_to_npm:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - run:
        command: npm publish
  polyfill_tests:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        name: Start test-server
        command: node ./test/polyfills/server.js
        background: true
    - run:
        name: Testing polyfills
        command: node ./test/polyfills/remotetest.js targeted
workflows:
  test:
    jobs:
    - lint_js:
        filters:
          tags:
            ignore: /^v.*/
          branches:
            ignore: master
    - unit_tests:
        filters:
          tags:
            ignore: /^v.*/
          branches:
            ignore: master
    - publish_to_npm:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - polyfill_tests:
        filters:
          tags:
            ignore: /^v.*/
          branches:
            ignore: master
        requires:
        - lint_js
        - unit_tests
  version: 2

# Original config.yml file:
# 
# version: 2.1
# jobs:
#   lint_js:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - run: npm ci
#       - run: npm run lint
#   unit_tests:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - run: npm ci
#       - run: npm run test-library
#   publish_to_npm:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - run: npm ci
#       - run: echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > ~/.npmrc
#       - run: npm publish
#   polyfill_tests:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - run: npm ci
#       - run:
#           name: Start test-server
#           command: node ./test/polyfills/server.js
#           background: true
#       - run:
#           name: Testing polyfills
#           command: node ./test/polyfills/remotetest.js targeted
# workflows:
#   test:
#     jobs:
#       - lint_js:
#           filters:
#             tags:
#               ignore: /^v.*/
#             branches:
#               ignore: master
#       - unit_tests:
#           filters:
#             tags:
#               ignore: /^v.*/
#             branches:
#               ignore: master
#       - publish_to_npm:
#           filters:
#             tags:
#               only: /^v.*/
#             branches:
#               ignore: /.*/
#       - polyfill_tests:
#           filters:
#             tags:
#               ignore: /^v.*/
#             branches:
#               ignore: master
#           requires:
#             - lint_js
#             - unit_tests