dependencies = [
  "Reflect",
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.Type",
  "_ESAbstract.ToPropertyKey",
  "_ESAbstract.HasOwnProperty"
]
spec = "https://tc39.github.io/ecma262/#sec-reflect.deleteproperty"

[browsers]
android = "*"
bb = "*"
chrome = "<79.0"
edge = "*"
edge_mob = "*"
firefox = "<68.0"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "<13.0"
samsung_mob = "*"
