aliases = [ ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToPropertyKey",
  "_ESAbstract.CreateDataPropertyOrThrow",
  "_ESAbstract.AddEntriesFromIterable"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries"
spec = "https://tc39.github.io/ecma262/#sec-object.fromentries"

[browsers]
android = "*"
bb = "*"
chrome = "<79.0"
edge = "*"
edge_mob = "*"
firefox = "<68.0"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "<13.0"
samsung_mob = "*"
