aliases = []
dependencies = [
    "Object.getOwnPropertyDescriptor",
    "Object.defineProperty",
    "Reflect.ownKeys",
    "Array.protoype.reduce"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors"

[browsers]
ie = "*"
edge = "<15"
chrome = "<54"
firefox = "<50"
safari = "<10"
